import type { ThemeConfig } from "antd";

const themeConfig: ThemeConfig = {
  token: {
    colorPrimary: "#C74634",
    colorSuccess: "#52c41a",
    colorWarning: "#faad14",
    colorError: "#d32f2f",
    colorInfo: "#1890ff",
    colorLink: "#C74634",
    colorTextBase: "#000000",
    colorBgBase: "#ffffff",
    fontFamily:
      '-apple-system, BlinkMacSystemFont, "Segoe UI", "Helvetica Neue", Arial, sans-serif',
    fontSize: 13,
    fontSizeHeading1: 32,
    fontSizeHeading2: 24,
    fontSizeHeading3: 18,
    fontSizeHeading4: 16,
    fontSizeHeading5: 14,
    borderRadius: 2,
    colorBorder: "#d9d9d9",
    colorBorderSecondary: "#e8e8e8",
    lineHeight: 1.5,
    controlHeight: 36,
    controlHeightLG: 40,
    controlHeightSM: 28,
    padding: 12,
    paddingLG: 16,
    paddingXS: 6,
    margin: 12,
    marginLG: 16,
    marginXS: 6,
  },
  components: {
    Layout: {
      headerBg: "#ffffff",
      headerHeight: 64,
      headerPadding: "0 40px",
      bodyBg: "#fafafa",
      footerBg: "#1a1a1a",
      footerPadding: "32px 40px",
    },
    Button: {
      primaryColor: "#ffffff",
      colorPrimary: "#C74634",
      colorPrimaryHover: "#a63829",
      colorPrimaryActive: "#8b2f21",
      defaultBorderColor: "#d9d9d9",
      defaultColor: "#000000",
      borderRadius: 2,
      controlHeight: 36,
      fontWeight: 500,
      paddingContentHorizontal: 20,
      fontSize: 13,
    },
    Input: {
      borderRadius: 2,
      colorBorder: "#d9d9d9",
      controlHeight: 36,
      fontSize: 13,
      paddingBlock: 8,
      paddingInline: 12,
    },
    Select: {
      borderRadius: 2,
      controlHeight: 36,
      fontSize: 13,
    },
    Card: {
      borderRadiusLG: 0,
      boxShadowTertiary: "0 1px 3px 0 rgba(0, 0, 0, 0.08)",
      paddingLG: 20,
      padding: 16,
    },
    Tag: {
      borderRadiusSM: 2,
      fontSizeSM: 11,
      lineHeightSM: 18,
    },
    Typography: {
      fontSizeHeading1: 32,
      fontSizeHeading2: 24,
      fontSizeHeading3: 18,
      fontSizeHeading4: 16,
      fontSizeHeading5: 14,
      fontWeightStrong: 600,
      titleMarginBottom: 0,
      titleMarginTop: 0,
    },
    Divider: {
      colorSplit: "#e8e8e8",
      margin: 16,
      marginLG: 20,
    },
    Space: {
      padding: 0,
    },
    Alert: {
      borderRadiusLG: 2,
      paddingContentHorizontalLG: 16,
    },
    Timeline: {
      dotBg: "#ffffff",
      tailColor: "#e8e8e8",
    },
    Form: {
      itemMarginBottom: 16,
      verticalLabelPadding: "0 0 4px",
    },
  },
};

export default themeConfig;
